-- MySQL Script generated by MySQL Workbench
-- Fri Dec 20 00:36:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chatApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatApp` DEFAULT CHARACTER SET latin1 ;
USE `chatApp` ;

-- -----------------------------------------------------
-- Table `chatApp`.`ActiveUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatApp`.`ActiveUser` (
  `GroupName` VARCHAR(80) NOT NULL,
  `UserID` VARCHAR(20) NOT NULL,
  `UserName` VARCHAR(30) NULL DEFAULT NULL,
  `lastActiveTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`GroupName`, `UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chatApp`.`Reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatApp`.`Reports` (
  `UserID` TEXT NOT NULL,
  `ReportedUserID` TEXT NOT NULL,
  `MessageID` TEXT NOT NULL,
  `ReportedMessage` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chatApp`.`UserWeight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatApp`.`UserWeight` (
  `UserID` VARCHAR(20) NOT NULL,
  `Weight` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chatApp`.`VotedUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatApp`.`VotedUser` (
  `VoteID` INT(11) NOT NULL,
  `UserID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VoteID`, `UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `chatApp`.`Votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatApp`.`Votes` (
  `VoteID` INT(11) NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(80) NOT NULL,
  `MessageID` VARCHAR(20) NOT NULL,
  `TotalVote` INT(11) NULL DEFAULT '0',
  `Message` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`VoteID`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
